ports:
  traefik:
    port: 9000
    expose:
      default: true
    exposedPort: 9000
    protocol: TCP

  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

entryPoints:
  traefik:
    address: ":9000"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

additionalArguments:
  - "--log.level=DEBUG"
  - "--api.dashboard=true"
  - "--api.insecure=true"

service:
  type: ClusterIP