apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-values
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack

data:
  values.yaml: |
    grafana:
      adminPassword: prom-operator
      service:
        type: ClusterIP
    prometheus:
      service:
        type: ClusterIP