# apps/argocd/overlays/local/kustomization.yaml
resources:
  - ../../base #ArgoCD installation manifest
  - argocd-app.yaml #Application Manifest for ArgoCD
  - monitoring-app.yaml #Application Manifest for monitoring

namespace: argocd

patches:
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--insecure"
      - op: replace
        path: /spec/replicas
        value: 1